### ISSUE TITLE
Sorry for being thick...

### ISSUE THREAD

**Issue by iammerrick** [dsibiski/react-native-embedded-app-example#7]
But how do I get RCTRootView etc in my load path?

**Comment by dsibiski** [comment]
Hmm, what do you mean by the "load path"? Do you mean on the native (Obj-C) side or in JS?

**Comment by iammerrick** [comment]
I mean on the native ObjC side. getting the libreact.a file built and in the right place to use it in an existing application.

**Comment by idibidiart** [comment]
Excuse me if I'm wrong but I think you can start with 'react-native init projectName' then add the Objective-C codebase to it. I wondered about that too.

btw @dsibiski  I have taken your Coordinator concept and implemented two-way data exchange between RN and ObjC views and it works great. Will have something to share soon, insight wise.

Let us know if the above suggestion is the way to go or if there is a better way? Thanks :)

**Comment by dsibiski** [comment]
@idibidiart That's one way, but sometimes you don't want to mess with your current repo & folder structure depending on the project.

@iammerrick , there are a couple different ways you can add it.

First, you can use Cocoapods: http://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods

That can be a little simpler to get going but not totally necessary.

Another way, would be to create a dir inside of your existing project (ie. "React") with a `package.json` inside of it like this:

``` json
{
  "name": "my-existing-app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "~0.12"
  }
}
```

Do an `npm i` from that directory and it will install React Native there. The next steps would be in Xcode:
1. Open your project in XCode, create a `Libraries` group if you don't already have one, right click on it and click `Add
   Files to "Your Project Name"`.
2. Select the `React.xcodeproj` file in the `node_modules/react-native` folder and click `Add`
3. In the Xcode Project Navigator find the `React.xcodproj` and add the  `Products/libReact.a` to `Build Phases -> Link Binary With Libraries`.

Next is to add the "Header Search Paths":

![header_search_paths](https://i.imgur.com/4O39K4X.png)
1. Click on the `Project` in Xcode
2. Click on your main `Target`
3. Search for `Header Search Paths`
4. Add the path to React from your `node_modules` folder, making sure so select `recursive`

Once you have the header search paths you should be able to import the headers in your Obj-C files.

You'll also need to add some of the other Libraries like: `RCTText`, `RCTNetworking`, etc...if you do a `react-native init` for a sample project you will see all the default ones included.

I hope this helps. I'll probably add this to the Readme at some point.

**Comment by idibidiart** [comment]
:+1:

**Comment by iammerrick** [comment]
@dsibiski Thank you so much! :-D

**Comment by dsibiski** [comment]
@iammerrick No problem. :+1:  Please feel free to open any more issues for other questions on your "hybrid" React Native experience. :)

**Comment by iammerrick** [comment]
Currently getting this error, do I need to specify platform somewhere in my request or code url?:
rror: Error validating module options: child "platform" fails because ["platform" is required]
    at /Users/Merrick/Developer/Domo/Hayabusa/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/Merrick/Developer/Domo/Hayabusa/node_modules/react-native/packager/react-packager/src/Server/index.js:161:20
    at tryCallOne (/Users/Merrick/Developer/Domo/Hayabusa/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/Merrick/Developer/Domo/Hayabusa/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/Merrick/Developer/Domo/Hayabusa/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by idibidiart** [comment]
hi @iammerrick 

I think in RN 0.12.0 and later you need to specify the platform (ios or android) in your AppDelegate.m:

```
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];
```

**Comment by dsibiski** [comment]
Thanks @idibidiart for answering!

**Comment by iammerrick** [comment]
Thank you both! :-D

**Comment by iammerrick** [comment]
Do I need to do more like compile plugins? Currently getting this error: https://github.com/facebook/react-native/issues/3154

**Comment by idibidiart** [comment]
hey @iammerrick 

I had that error after upgrading to 0.13.0-rc. I resolved that by killing the packager process (see your terminal windows) and restarting it with `npm start` 

I also did other things before that like deleting the app from simulator but they didn't seem to have an effect until I restarted the packager.

I run this, which I have in my .bash_profile, which deletes XCode derived data. It’s the location where Xcode stores all kinds of intermediate build results, generated indexes, etc.

ddd() {
#Save the starting dir
startingDir=$PWD
#Go to the derivedData
cd ~/Library/Developer/Xcode/DerivedData
#Sometimes, 1 file remains, so loop until no files remain
numRemainingFiles=1
while [ $numRemainingFiles -gt 0 ]; do
#Delete the files, recursively
rm -rf *
#Update file count
numRemainingFiles=ls | wc -l
done
echo Done
#Go back to starting dir
cd $startingDir
}

then I restarted XCode, cleaned, removed app from Simulator

restarted packager

then rebuilt

It works fine now (at least for me) but this needs to be traced to the root cause and resolved properly
